# raw:
#   presenters:
#     table:
#       shown_columns:
#         - timestamp
#         - timespan
#         - cycle
#         - n_cycle
#         - pc
#       formatter:
#         pc: '{:x}'

flow:
  verbose: True
  # x_axis: cycle

latency:
  measurements:
    - name: count_1s_0s
      start: "pc == 0x100414"
      stop: "pc == 0x100430"
